mode: train # train, test
gpu_no: 0
version: unet-dice
model:
    type: unet # deeplabv3p, attentionunet
dataset:
    data_path: ./lgg-mri-segmentation
    batch_size: 16
augmentation:
    grid_distort: 0.1
    elastic_deform: 0.1
    histeq: 0.1
optimizer:
    beta_1: 0.9
    beta_2: 0.98
training:
    epochs: 100
    print_iter: 10
    save_epoch: 5
    init_learning_rate: 0.001
    bce_loss_weight: 1
    dice_loss_weight: 1
    save_path: ./save
test:
    epoch: False
deeplabv3p:
    backbone: xception
    output_stride: 8
unet:
    n_filter: 64
    n_blocks: 5
    tconv: False
attentionunet:
    n_filter: 64
    n_blocks: 5
    tconv: False
